name: matokeo_core
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Edwin Magabe <email@example.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  path: ^1.6.0
  path_provider: ^1.4.5
  rxdart: ^0.22.4
  http: ^0.12.0+2
  petitparser: ^2.4.0
  xml: ^3.5.0
  equatable: ^1.0.1
  magabe_simple_smart_scraper:
   git:
     url: A:/DART_PROJECTS/magabe_simple_smart_scraper/.git

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
